import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "zh" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    // Header
    "app.name": "SalesCore",
    "app.subtitle": "销售智能终端",
    "auth.login": "登录 / 注册",
    "auth.logout": "退出登录",
    "auth.logged_in": "已登录",
    "auth.sync_data": "登录以同步您的数据",
    
    // Tabs
    "tab.inbox": "语音箱",
    "tab.ai_chat": "AI助手",
    "tab.toolkit": "工具箱",
    "tab.ai_chat_full": "AI 对话助手",
    "tab.toolkit_full": "现场工具箱",
    
    // Menu items
    "menu.hardware": "硬件伴侣",
    "menu.hardware_desc": "设备管理与同步",
    "menu.leads": "我的线索",
    "menu.leads_desc": "查看跟进记录",
    "menu.opportunities": "我的商机",
    "menu.opportunities_desc": "活动与报价",
    "menu.dashboard": "管理驾驶舱",
    "menu.dashboard_desc": "销售地图 · 胜任力分析",
    
    // Smart Inbox
    "inbox.empty": "收件箱已清空",
    "inbox.empty_desc": "所有任务已处理完毕",
    "inbox.approved": "已批准入库",
    "inbox.lead_updated": "线索信息已更新到 aiCRM",
    "inbox.opp_updated": "商机信息已更新到 aiCRM",
    "inbox.transcript": "转录文本 · 点击查看完整内容",
    "inbox.ai_extracted": "AI 提取字段",
    "inbox.ai_suggestions": "AI 建议动作",
    "inbox.click_edit": "点击编辑后批准入库",
    "inbox.edit_approve": "编辑并批准入库",
    "inbox.view_detail": "查看详情",
    "inbox.status.pending": "待处理",
    "inbox.status.analyzing": "AI 分析中",
    "inbox.status.approved": "已入库",
    "inbox.status.archived": "已归档",
    "inbox.type.voice": "语音补录",
    "inbox.type.call": "电话拜访",
    "inbox.type.meeting": "会议记录",
    "inbox.confidence.high": "高",
    "inbox.confidence.medium": "中",
    "inbox.confidence.low": "低",
    "inbox.recording_start": "开始录音",
    "inbox.recording_stop": "再次点击停止",
    "inbox.voice_complete": "语音识别完成",
    "inbox.generating": "正在生成商机卡片...",
    "inbox.card_generated": "商机卡片已生成",
    "inbox.added_inbox": "已添加到收件箱",
    "inbox.mark_updated": "标记已更新",
    "inbox.location_on": "已开启定位",
    "inbox.location_off": "点击开启定位",
    
    // Fields
    "field.phone": "联系电话",
    "field.email": "电子邮箱",
    "field.budget": "预算范围",
    "field.next_followup": "下次跟进",
    "field.amount": "金额",
    "field.probability": "赢率",
    "field.expected_close": "预计成交",
    "field.requirements": "需求描述",
    "field.decision_maker": "决策人",
    "field.risk": "风险提示",
    
    // AI Chat
    "chat.start": "开始对话",
    "chat.start_desc": "向AI助手提问，获取业务洞察和智能建议",
    "chat.input_placeholder": "输入消息...",
    "chat.disclaimer": "AI助手可能会出错，请核实重要信息",
    "chat.voice_start": "开始录音...",
    "chat.voice_end": "录音已结束，正在识别...",
    "chat.voice_hold": "长按说话",
    "chat.voice_release": "松开发送",
    "chat.error": "发送消息失败，请重试",
    "chat.rate_limit": "请求过于频繁，请稀后再试",
    "chat.quota_exceeded": "AI额度不足，请充值后继续使用",
    
    // Field Toolkit
    "toolkit.voice_memo": "语音补录",
    "toolkit.voice_memo_desc": "快速录音备忘",
    "toolkit.card_scan": "名片扫描",
    "toolkit.card_scan_desc": "OCR 识别录入",
    "toolkit.recent": "最近记录",
    "toolkit.no_records": "暂无记录",
    "toolkit.voice": "语音",
    "toolkit.card": "名片",
    "toolkit.processing": "处理中",
    "toolkit.tip_voice": "应对突发场景",
    "toolkit.tip_voice_desc": "会议结束后发现忘记录音？使用语音补录功能，AI 会自动生成结构化待办。",
    "toolkit.tip_card": "名片快速录入",
    "toolkit.tip_card_desc": "拍照扫描客户名片，自动识别并填入 aiCRM 联系人字段，支持中/日/英多国格式。",
    "toolkit.quick_record": "快速记录重要信息",
    "toolkit.text_note": "或者输入文字备注...",
    "toolkit.hold_record": "按住录音",
    "toolkit.cancel": "取消",
    "toolkit.recording": "录音中...",
    "toolkit.stop_record": "停止录音",
    "toolkit.photo_upload": "点击拍照或上传",
    "toolkit.save_crm": "保存到 aiCRM",
    "toolkit.card_saved": "新名片已保存至 aiCRM",
    "toolkit.voice_saved": "新的语音备忘录已保存，AI 正在分析中...",
    "toolkit.name": "姓名",
    "toolkit.company": "公司",
    "toolkit.phone": "电话",
    "toolkit.email": "邮箱",

    // Dashboard
    "dashboard.title": "管理驾驶舱",
    "dashboard.subtitle": "Management Dashboard",
    "dashboard.realtime": "实时更新",
    "dashboard.tab.map": "销售地图",
    "dashboard.tab.leaderboard": "排行榜",
    "dashboard.tab.competency": "胜任力",
    "dashboard.tab.trends": "业务趋势",
    "dashboard.tab.stats": "数据统计",
    "dashboard.stats.voice_records": "语音记录",
    "dashboard.stats.leads": "线索数量",
    "dashboard.stats.opportunities": "商机数量",
    "dashboard.stats.quotes": "报价数量",
    "dashboard.stats.vs_last_month": "较上月",
    "dashboard.stats.conversion_rates": "转化率分析",
    "dashboard.stats.voice_to_lead": "语音 → 线索",
    "dashboard.stats.lead_to_opportunity": "线索 → 商机",
    "dashboard.stats.opportunity_to_quote": "商机 → 报价",
    "dashboard.stats.quote_to_deal": "报价 → 成交",
    "dashboard.stats.monthly_trend": "本周数据",
    "dashboard.stats.this_week": "本周",
    "dashboard.champion_sales": "本月冠军业绩",
    "dashboard.team_avg_rate": "团队平均完成率",
    "dashboard.monthly_deals": "本月总成交数",
    "dashboard.monthly_leaderboard": "本月销售排行榜",
    "dashboard.month": "11月",
    "dashboard.deals": "成交",
    "dashboard.deals_count": "单",
    "dashboard.new_leads": "新增",
    "dashboard.leads_unit": "线索",
    "dashboard.monthly_performance": "本月业绩",
    "dashboard.completion_rate": "完成率",
    "dashboard.champion": "冠军",
    "dashboard.runner_up": "亚军",
    "dashboard.third_place": "季军",
    "dashboard.rank": "第",
    "dashboard.rank_suffix": "名",
    "dashboard.team_monthly_overview": "团队月度目标总览",
    "dashboard.team_target": "团队总目标",
    "dashboard.completed": "已完成",
    "dashboard.remaining": "还需完成",
    "dashboard.on_target": "达标人数",
    "dashboard.sprint_needed": "待冲刺",
    "dashboard.person": "人",
    "dashboard.team_map": "团队外勤实时地图",
    "dashboard.map_view": "地图视图",
    "dashboard.map_integration": "集成地图服务后将显示实时位置",
    "dashboard.visit_heatmap": "今日拜访热力",
    "dashboard.visits": "次拜访",
    "dashboard.team_members": "团队成员",
    "dashboard.points": "分",
    "dashboard.competency_analysis": "销售能力分析",
    "dashboard.overall_score": "综合评分",
    "dashboard.detail_scores": "能力详细评分",
    "dashboard.ai_suggestions": "AI 改进建议",
    "dashboard.suggestion_1": "促成技巧较弱，建议加强逼单话术培训",
    "dashboard.suggestion_2": "异议处理能力需提升，可参考优秀案例",
    "dashboard.suggestion_3": "需求挖掘能力优秀，保持现有水平",
    "dashboard.global_funnel": "全局转化漏斗",
    "dashboard.keyword_analysis": "高频关键词分析",
    "dashboard.keyword_source": "基于通话录音AI提取",
    "dashboard.objection_types": "异议类型分布",
    "dashboard.price_objection": "价格异议",
    "dashboard.time_process_objection": "时间/流程异议",
    "dashboard.positive_feedback": "正面反馈",
    "dashboard.feature_request": "功能需求",
    "dashboard.times": "次",
    "dashboard.basic_info": "基本信息",
    "dashboard.phone": "联系电话",
    "dashboard.email": "电子邮箱",
    "dashboard.department": "所属部门",
    "dashboard.monthly_target": "本月目标",
    "dashboard.monthly_sales": "本月业绩",
    "dashboard.closed_deals": "成交订单",
    "dashboard.new_leads_count": "新增线索",
    "dashboard.monthly_trend": "月度业绩趋势",
    "dashboard.deal_records": "成交记录",
    "dashboard.customer_list": "客户列表",
    "dashboard.closed": "成交",
    "dashboard.following": "跟进中",
    "dashboard.deal_closed": "已成交",
    // Competency subjects
    "competency.speech_compliance": "话术合规性",
    "competency.objection_handling": "异议处理",
    "competency.needs_discovery": "需求挖掘",
    "competency.product_intro": "产品介绍",
    "competency.closing_skills": "促成技巧",
    "competency.relationship": "客情维护",
    // Funnel stages
    "funnel.total_leads": "线索总数",
    "funnel.contacted": "已联系",
    "funnel.confirmed": "已确认",
    "funnel.opportunity": "商机创建",
    "funnel.proposal": "方案提交",
    "funnel.closed": "成交",
    // Word cloud
    "word.price_high": "价格太高",
    "word.consider": "考虑一下",
    "word.budget_low": "预算不足",
    "word.need_approval": "需要审批",
    "word.competitor_cheaper": "竞品便宜",
    "word.feature_lacking": "功能不够",
    "word.very_interested": "很感兴趣",
    "word.contact_next_week": "下周联系",
    "word.no_time": "时间不够",
    "word.good_proposal": "方案不错",
    "word.need_compare": "需要对比",
    "word.boss_decide": "老板决定",
    // Locations
    "location.shanghai_pudong": "上海浦东",
    "location.beijing_chaoyang": "北京朝阳",
    "location.shenzhen_nanshan": "深圳南山",
    "location.shanghai_jingan": "上海静安",
    "location.chengdu_gaoxin": "成都高新",
    // Time
    "time.hours_ago": "小时前",
    "time.minutes_ago": "分钟前",
  },
  en: {
    // Header
    "app.name": "SalesCore",
    "app.subtitle": "Sales Intelligence Terminal",
    "auth.login": "Login / Sign Up",
    "auth.logout": "Log Out",
    "auth.logged_in": "Logged In",
    "auth.sync_data": "Sign in to sync your data",
    
    // Tabs
    "tab.inbox": "Voice Box",
    "tab.ai_chat": "AI Chat",
    "tab.toolkit": "Toolkit",
    "tab.ai_chat_full": "AI Chat Assistant",
    "tab.toolkit_full": "Field Toolkit",
    
    // Menu items
    "menu.hardware": "Hardware Companion",
    "menu.hardware_desc": "Device management & sync",
    "menu.leads": "My Leads",
    "menu.leads_desc": "View follow-up records",
    "menu.opportunities": "My Opportunities",
    "menu.opportunities_desc": "Activities & quotes",
    "menu.dashboard": "Dashboard",
    "menu.dashboard_desc": "Sales map · Performance analysis",
    
    // Smart Inbox
    "inbox.empty": "Inbox Cleared",
    "inbox.empty_desc": "All tasks have been processed",
    "inbox.approved": "Approved",
    "inbox.lead_updated": "Lead info updated to aiCRM",
    "inbox.opp_updated": "Opportunity info updated to aiCRM",
    "inbox.transcript": "Transcript · Click to view full content",
    "inbox.ai_extracted": "AI Extracted Fields",
    "inbox.ai_suggestions": "AI Suggested Actions",
    "inbox.click_edit": "Click to edit and approve",
    "inbox.edit_approve": "Edit & Approve",
    "inbox.view_detail": "View Details",
    "inbox.status.pending": "Pending",
    "inbox.status.analyzing": "AI Analyzing",
    "inbox.status.approved": "Approved",
    "inbox.status.archived": "Archived",
    "inbox.type.voice": "Voice Memo",
    "inbox.type.call": "Phone Call",
    "inbox.type.meeting": "Meeting Record",
    "inbox.confidence.high": "High",
    "inbox.confidence.medium": "Medium",
    "inbox.confidence.low": "Low",
    "inbox.recording_start": "Recording started",
    "inbox.recording_stop": "Click again to stop",
    "inbox.voice_complete": "Voice recognition complete",
    "inbox.generating": "Generating opportunity card...",
    "inbox.card_generated": "Opportunity card generated",
    "inbox.added_inbox": "Added to inbox",
    "inbox.mark_updated": "Mark updated",
    "inbox.location_on": "Location enabled",
    "inbox.location_off": "Click to enable location",
    
    // Fields
    "field.phone": "Phone",
    "field.email": "Email",
    "field.budget": "Budget",
    "field.next_followup": "Next Follow-up",
    "field.amount": "Amount",
    "field.probability": "Win Rate",
    "field.expected_close": "Expected Close",
    "field.requirements": "Requirements",
    "field.decision_maker": "Decision Maker",
    "field.risk": "Risk Alert",
    
    // AI Chat
    "chat.start": "Start Conversation",
    "chat.start_desc": "Ask AI assistant for business insights and smart suggestions",
    "chat.input_placeholder": "Type a message...",
    "chat.disclaimer": "AI assistant may make mistakes. Please verify important information",
    "chat.voice_start": "Recording started...",
    "chat.voice_end": "Recording ended, recognizing...",
    "chat.voice_hold": "Hold to Talk",
    "chat.voice_release": "Release to Send",
    "chat.error": "Failed to send message, please retry",
    "chat.rate_limit": "Too many requests, please try again later",
    "chat.quota_exceeded": "AI quota exceeded, please recharge",
    
    // Field Toolkit
    "toolkit.voice_memo": "Voice Memo",
    "toolkit.voice_memo_desc": "Quick voice notes",
    "toolkit.card_scan": "Card Scanner",
    "toolkit.card_scan_desc": "OCR recognition",
    "toolkit.recent": "Recent Records",
    "toolkit.no_records": "No records yet",
    "toolkit.voice": "Voice",
    "toolkit.card": "Card",
    "toolkit.processing": "Processing",
    "toolkit.tip_voice": "Handle unexpected situations",
    "toolkit.tip_voice_desc": "Forgot to record after a meeting? Use voice memo feature, AI will auto-generate structured to-dos.",
    "toolkit.tip_card": "Quick card entry",
    "toolkit.tip_card_desc": "Scan business cards, auto-recognize and fill into aiCRM contact fields. Supports multiple formats.",
    "toolkit.quick_record": "Quick record important info",
    "toolkit.text_note": "Or type a text note...",
    "toolkit.hold_record": "Hold to Record",
    "toolkit.cancel": "Cancel",
    "toolkit.recording": "Recording...",
    "toolkit.stop_record": "Stop Recording",
    "toolkit.photo_upload": "Click to capture or upload",
    "toolkit.save_crm": "Save to aiCRM",
    "toolkit.card_saved": "Business card saved to aiCRM",
    "toolkit.voice_saved": "Voice memo saved, AI is analyzing...",
    "toolkit.name": "Name",
    "toolkit.company": "Company",
    "toolkit.phone": "Phone",
    "toolkit.email": "Email",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Management Dashboard",
    "dashboard.realtime": "Real-time",
    "dashboard.tab.map": "Sales Map",
    "dashboard.tab.leaderboard": "Leaderboard",
    "dashboard.tab.competency": "Competency",
    "dashboard.tab.trends": "Trends",
    "dashboard.tab.stats": "Statistics",
    "dashboard.stats.voice_records": "Voice Records",
    "dashboard.stats.leads": "Leads",
    "dashboard.stats.opportunities": "Opportunities",
    "dashboard.stats.quotes": "Quotes",
    "dashboard.stats.vs_last_month": "vs last month",
    "dashboard.stats.conversion_rates": "Conversion Rates",
    "dashboard.stats.voice_to_lead": "Voice → Lead",
    "dashboard.stats.lead_to_opportunity": "Lead → Opportunity",
    "dashboard.stats.opportunity_to_quote": "Opportunity → Quote",
    "dashboard.stats.quote_to_deal": "Quote → Deal",
    "dashboard.stats.monthly_trend": "This Week's Data",
    "dashboard.stats.this_week": "This Week",
    "dashboard.champion_sales": "Champion Sales",
    "dashboard.team_avg_rate": "Team Avg Rate",
    "dashboard.monthly_deals": "Monthly Deals",
    "dashboard.monthly_leaderboard": "Monthly Sales Leaderboard",
    "dashboard.month": "Nov",
    "dashboard.deals": "Deals",
    "dashboard.deals_count": "",
    "dashboard.new_leads": "New",
    "dashboard.leads_unit": "leads",
    "dashboard.monthly_performance": "Monthly Sales",
    "dashboard.completion_rate": "Completion",
    "dashboard.champion": "Champion",
    "dashboard.runner_up": "Runner-up",
    "dashboard.third_place": "3rd Place",
    "dashboard.rank": "Rank",
    "dashboard.rank_suffix": "",
    "dashboard.team_monthly_overview": "Team Monthly Target Overview",
    "dashboard.team_target": "Team Target",
    "dashboard.completed": "Completed",
    "dashboard.remaining": "Remaining",
    "dashboard.on_target": "On Target",
    "dashboard.sprint_needed": "Sprint Needed",
    "dashboard.person": "",
    "dashboard.team_map": "Team Field Map",
    "dashboard.map_view": "Map View",
    "dashboard.map_integration": "Real-time locations after map integration",
    "dashboard.visit_heatmap": "Today's Visit Heatmap",
    "dashboard.visits": "visits",
    "dashboard.team_members": "Team Members",
    "dashboard.points": "pts",
    "dashboard.competency_analysis": "Sales Competency Analysis",
    "dashboard.overall_score": "Overall Score",
    "dashboard.detail_scores": "Detailed Scores",
    "dashboard.ai_suggestions": "AI Suggestions",
    "dashboard.suggestion_1": "Closing skills need improvement, recommend sales training",
    "dashboard.suggestion_2": "Objection handling needs work, review best practices",
    "dashboard.suggestion_3": "Excellent needs discovery skills, maintain current level",
    "dashboard.global_funnel": "Global Conversion Funnel",
    "dashboard.keyword_analysis": "High-Frequency Keywords",
    "dashboard.keyword_source": "AI extracted from call recordings",
    "dashboard.objection_types": "Objection Type Distribution",
    "dashboard.price_objection": "Price Objection",
    "dashboard.time_process_objection": "Time/Process Objection",
    "dashboard.positive_feedback": "Positive Feedback",
    "dashboard.feature_request": "Feature Request",
    "dashboard.times": "times",
    "dashboard.basic_info": "Basic Info",
    "dashboard.phone": "Phone",
    "dashboard.email": "Email",
    "dashboard.department": "Department",
    "dashboard.monthly_target": "Monthly Target",
    "dashboard.monthly_sales": "Monthly Sales",
    "dashboard.closed_deals": "Closed Deals",
    "dashboard.new_leads_count": "New Leads",
    "dashboard.monthly_trend": "Monthly Sales Trend",
    "dashboard.deal_records": "Deal Records",
    "dashboard.customer_list": "Customer List",
    "dashboard.closed": "Closed",
    "dashboard.following": "Following",
    "dashboard.deal_closed": "Closed",
    // Competency subjects
    "competency.speech_compliance": "Speech Compliance",
    "competency.objection_handling": "Objection Handling",
    "competency.needs_discovery": "Needs Discovery",
    "competency.product_intro": "Product Intro",
    "competency.closing_skills": "Closing Skills",
    "competency.relationship": "Relationship Mgmt",
    // Funnel stages
    "funnel.total_leads": "Total Leads",
    "funnel.contacted": "Contacted",
    "funnel.confirmed": "Confirmed",
    "funnel.opportunity": "Opportunity",
    "funnel.proposal": "Proposal",
    "funnel.closed": "Closed",
    // Word cloud
    "word.price_high": "Too expensive",
    "word.consider": "Need to think",
    "word.budget_low": "Budget limited",
    "word.need_approval": "Need approval",
    "word.competitor_cheaper": "Competitor cheaper",
    "word.feature_lacking": "Missing features",
    "word.very_interested": "Very interested",
    "word.contact_next_week": "Contact next week",
    "word.no_time": "No time",
    "word.good_proposal": "Good proposal",
    "word.need_compare": "Need to compare",
    "word.boss_decide": "Boss decides",
    // Locations
    "location.shanghai_pudong": "Shanghai Pudong",
    "location.beijing_chaoyang": "Beijing Chaoyang",
    "location.shenzhen_nanshan": "Shenzhen Nanshan",
    "location.shanghai_jingan": "Shanghai Jingan",
    "location.chengdu_gaoxin": "Chengdu Hi-tech",
    // Time
    "time.hours_ago": "hours ago",
    "time.minutes_ago": "minutes ago",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "zh";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations["zh"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
